/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsNumber,
  ValidateNested,
} from "class-validator";
import { RestaurantEntityUpdateManyWithoutUtilisateursInput } from "./RestaurantEntityUpdateManyWithoutUtilisateursInput";
import { Type } from "class-transformer";
import { RestaurantUpdateManyWithoutUtilisateursInput } from "./RestaurantUpdateManyWithoutUtilisateursInput";

@InputType()
class UtilisateurUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  localisationLat?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  localisationLon?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  motDePasse?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nom?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nomEntiteJuridique?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  numeroTelephone?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  numeroTva?: string | null;

  @ApiProperty({
    required: false,
    type: () => RestaurantEntityUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => RestaurantEntityUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => RestaurantEntityUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  restaurantEntities?: RestaurantEntityUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: () => RestaurantUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => RestaurantUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => RestaurantUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  restaurants?: RestaurantUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  typeCommerce?: string | null;
}

export { UtilisateurUpdateInput as UtilisateurUpdateInput };
