/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RemboursementService } from "../remboursement.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RemboursementCreateInput } from "./RemboursementCreateInput";
import { Remboursement } from "./Remboursement";
import { RemboursementFindManyArgs } from "./RemboursementFindManyArgs";
import { RemboursementWhereUniqueInput } from "./RemboursementWhereUniqueInput";
import { RemboursementUpdateInput } from "./RemboursementUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RemboursementControllerBase {
  constructor(
    protected readonly service: RemboursementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Remboursement })
  @nestAccessControl.UseRoles({
    resource: "Remboursement",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: RemboursementCreateInput,
  })
  async createRemboursement(
    @common.Body() data: RemboursementCreateInput
  ): Promise<Remboursement> {
    return await this.service.createRemboursement({
      data: {
        ...data,

        vente: data.vente
          ? {
              connect: data.vente,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        dateRemboursement: true,
        id: true,
        montant: true,
        updatedAt: true,

        vente: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Remboursement] })
  @ApiNestedQuery(RemboursementFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Remboursement",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async remboursements(
    @common.Req() request: Request
  ): Promise<Remboursement[]> {
    const args = plainToClass(RemboursementFindManyArgs, request.query);
    return this.service.remboursements({
      ...args,
      select: {
        createdAt: true,
        dateRemboursement: true,
        id: true,
        montant: true,
        updatedAt: true,

        vente: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Remboursement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Remboursement",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async remboursement(
    @common.Param() params: RemboursementWhereUniqueInput
  ): Promise<Remboursement | null> {
    const result = await this.service.remboursement({
      where: params,
      select: {
        createdAt: true,
        dateRemboursement: true,
        id: true,
        montant: true,
        updatedAt: true,

        vente: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Remboursement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Remboursement",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: RemboursementUpdateInput,
  })
  async updateRemboursement(
    @common.Param() params: RemboursementWhereUniqueInput,
    @common.Body() data: RemboursementUpdateInput
  ): Promise<Remboursement | null> {
    try {
      return await this.service.updateRemboursement({
        where: params,
        data: {
          ...data,

          vente: data.vente
            ? {
                connect: data.vente,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          dateRemboursement: true,
          id: true,
          montant: true,
          updatedAt: true,

          vente: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Remboursement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Remboursement",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRemboursement(
    @common.Param() params: RemboursementWhereUniqueInput
  ): Promise<Remboursement | null> {
    try {
      return await this.service.deleteRemboursement({
        where: params,
        select: {
          createdAt: true,
          dateRemboursement: true,
          id: true,
          montant: true,
          updatedAt: true,

          vente: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
