/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RefundService } from "../refund.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RefundCreateInput } from "./RefundCreateInput";
import { Refund } from "./Refund";
import { RefundFindManyArgs } from "./RefundFindManyArgs";
import { RefundWhereUniqueInput } from "./RefundWhereUniqueInput";
import { RefundUpdateInput } from "./RefundUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RefundControllerBase {
  constructor(
    protected readonly service: RefundService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Refund })
  @nestAccessControl.UseRoles({
    resource: "Refund",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: RefundCreateInput,
  })
  async createRefund(@common.Body() data: RefundCreateInput): Promise<Refund> {
    return await this.service.createRefund({
      data: {
        ...data,

        vente: data.vente
          ? {
              connect: data.vente,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        dateRemboursement: true,
        id: true,
        montant: true,
        updatedAt: true,

        vente: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Refund] })
  @ApiNestedQuery(RefundFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Refund",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async refunds(@common.Req() request: Request): Promise<Refund[]> {
    const args = plainToClass(RefundFindManyArgs, request.query);
    return this.service.refunds({
      ...args,
      select: {
        createdAt: true,
        dateRemboursement: true,
        id: true,
        montant: true,
        updatedAt: true,

        vente: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Refund })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Refund",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async refund(
    @common.Param() params: RefundWhereUniqueInput
  ): Promise<Refund | null> {
    const result = await this.service.refund({
      where: params,
      select: {
        createdAt: true,
        dateRemboursement: true,
        id: true,
        montant: true,
        updatedAt: true,

        vente: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Refund })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Refund",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: RefundUpdateInput,
  })
  async updateRefund(
    @common.Param() params: RefundWhereUniqueInput,
    @common.Body() data: RefundUpdateInput
  ): Promise<Refund | null> {
    try {
      return await this.service.updateRefund({
        where: params,
        data: {
          ...data,

          vente: data.vente
            ? {
                connect: data.vente,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          dateRemboursement: true,
          id: true,
          montant: true,
          updatedAt: true,

          vente: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Refund })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Refund",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRefund(
    @common.Param() params: RefundWhereUniqueInput
  ): Promise<Refund | null> {
    try {
      return await this.service.deleteRefund({
        where: params,
        select: {
          createdAt: true,
          dateRemboursement: true,
          id: true,
          montant: true,
          updatedAt: true,

          vente: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
