/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FoodBasketCreateNestedManyWithoutRestaurantsInput } from "./FoodBasketCreateNestedManyWithoutRestaurantsInput";
import {
  ValidateNested,
  IsOptional,
  IsNumber,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { PanierCreateNestedManyWithoutRestaurantsInput } from "./PanierCreateNestedManyWithoutRestaurantsInput";
import { UtilisateurWhereUniqueInput } from "../../utilisateur/base/UtilisateurWhereUniqueInput";

@InputType()
class RestaurantCreateInput {
  @ApiProperty({
    required: false,
    type: () => FoodBasketCreateNestedManyWithoutRestaurantsInput,
  })
  @ValidateNested()
  @Type(() => FoodBasketCreateNestedManyWithoutRestaurantsInput)
  @IsOptional()
  @Field(() => FoodBasketCreateNestedManyWithoutRestaurantsInput, {
    nullable: true,
  })
  foodBaskets?: FoodBasketCreateNestedManyWithoutRestaurantsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  localisationLat?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  localisationLon?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nom?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  numeroTelephone?: string | null;

  @ApiProperty({
    required: false,
    type: () => PanierCreateNestedManyWithoutRestaurantsInput,
  })
  @ValidateNested()
  @Type(() => PanierCreateNestedManyWithoutRestaurantsInput)
  @IsOptional()
  @Field(() => PanierCreateNestedManyWithoutRestaurantsInput, {
    nullable: true,
  })
  paniers?: PanierCreateNestedManyWithoutRestaurantsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  typeCommerce?: string | null;

  @ApiProperty({
    required: false,
    type: () => UtilisateurWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UtilisateurWhereUniqueInput)
  @IsOptional()
  @Field(() => UtilisateurWhereUniqueInput, {
    nullable: true,
  })
  utilisateur?: UtilisateurWhereUniqueInput | null;
}

export { RestaurantCreateInput as RestaurantCreateInput };
