/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CancellationService } from "../cancellation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CancellationCreateInput } from "./CancellationCreateInput";
import { Cancellation } from "./Cancellation";
import { CancellationFindManyArgs } from "./CancellationFindManyArgs";
import { CancellationWhereUniqueInput } from "./CancellationWhereUniqueInput";
import { CancellationUpdateInput } from "./CancellationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CancellationControllerBase {
  constructor(
    protected readonly service: CancellationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Cancellation })
  @nestAccessControl.UseRoles({
    resource: "Cancellation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: CancellationCreateInput,
  })
  async createCancellation(
    @common.Body() data: CancellationCreateInput
  ): Promise<Cancellation> {
    return await this.service.createCancellation({
      data: {
        ...data,

        panier: data.panier
          ? {
              connect: data.panier,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        dateAnnulation: true,
        id: true,

        panier: {
          select: {
            id: true,
          },
        },

        raison: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Cancellation] })
  @ApiNestedQuery(CancellationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Cancellation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cancellations(@common.Req() request: Request): Promise<Cancellation[]> {
    const args = plainToClass(CancellationFindManyArgs, request.query);
    return this.service.cancellations({
      ...args,
      select: {
        createdAt: true,
        dateAnnulation: true,
        id: true,

        panier: {
          select: {
            id: true,
          },
        },

        raison: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Cancellation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Cancellation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cancellation(
    @common.Param() params: CancellationWhereUniqueInput
  ): Promise<Cancellation | null> {
    const result = await this.service.cancellation({
      where: params,
      select: {
        createdAt: true,
        dateAnnulation: true,
        id: true,

        panier: {
          select: {
            id: true,
          },
        },

        raison: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Cancellation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Cancellation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: CancellationUpdateInput,
  })
  async updateCancellation(
    @common.Param() params: CancellationWhereUniqueInput,
    @common.Body() data: CancellationUpdateInput
  ): Promise<Cancellation | null> {
    try {
      return await this.service.updateCancellation({
        where: params,
        data: {
          ...data,

          panier: data.panier
            ? {
                connect: data.panier,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          dateAnnulation: true,
          id: true,

          panier: {
            select: {
              id: true,
            },
          },

          raison: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Cancellation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Cancellation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCancellation(
    @common.Param() params: CancellationWhereUniqueInput
  ): Promise<Cancellation | null> {
    try {
      return await this.service.deleteCancellation({
        where: params,
        select: {
          createdAt: true,
          dateAnnulation: true,
          id: true,

          panier: {
            select: {
              id: true,
            },
          },

          raison: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
